### ISSUE TITLE
Provide auth.json example

### ISSUE THREAD

**Issue by matthiasschoger** [OneMoreByte/hydroxide-container#4]
Hi all,

maybe I'm dense, but it would be great to have an example and documentation available for the auth.json format.

Tried Google, the main project and the ProtonMail docs, but couldn't find anything.

Thanks in advance.

**Comment by matthiasschoger** [comment]
The reason why I'm asking is that I'm getting an error when bootstrapping from environment variables.

When doing a fresh startup with user/password in the environment variables, I'm getting the following error. Tried to also set the HYDROXIDE_DEBUG = "true" environment variable, but I don't see any additional output on stdout or stderr.

Traceback (most recent call last):
  File "/app/entrypoint", line 121, in <module>
    main(sys.argv)
  File "/app/entrypoint", line 32, in main
    do_auth(PROTON_USER, PROTON_PASS)
  File "/app/entrypoint", line 76, in do_auth
    print(f"Bridge password: '{bridge_password}'")
UnboundLocalError: local variable 'bridge_password' referenced before assignment

**Comment by OneMoreByte** [comment]
This project is pretty old. I haven't touched it in a while. You might be better off forking it and updating it. Hydroxide is probably wildly out of date.
